default:
    target: {{ cookiecutter.target_schema }}
    outputs:
      {{ cookiecutter.target_schema }}:
        type: {{ cookiecutter.database_type }}

        # More information for the options in this file
        # can be found here: https://docs.getdbt.com/dbt-cli/configure-your-profile

        threads: 8

        {%- if cookiecutter.database_type == "postgres" %}
        # Additional PostgreSQL options
        # Find out more about PostgreSQL config options here:
        # https://docs.getdbt.com/reference/warehouse-profiles/postgres-profile

        # Set the TEST_DATABASE in your CI
        dbname: {% raw %}"{{ env_var('DBT_DATABASE') }}"{% endraw %}
        schema: {% raw %}"{{ env_var('DBT_SCHEMA') }}"{% endraw %}

        # Set variable DBT_USER in your CI
        user: {% raw %}"{{ env_var('DBT_USER') }}"{% endraw %}

        # Set variable DBT_PASSWORD in your CI
        password: {% raw %}"{{ env_var('DBT_PASSWORD') }}"{% endraw %}

        # Set variable DBT_REDSHIFT_ACCOUNT in your CI
        host: {% raw %}"{{ env_var('DBT_HOST') }}"{% endraw %}

        port: 5439
        keepalives_idle: 10 # default 0, indicating the system default
        # search_path: public # optional, not recommended
        # sslmode: [optional, set the sslmode used to connect to the database (in case this parameter is set, will look for ca in ~/.postgresql/root.crt)]
        {%- endif %}

        {%- if cookiecutter.database_type == "redshift" %}
        # Additional Redshift options
        # Find out more about Redshift config options here:
        # https://docs.getdbt.com/reference/warehouse-profiles/redshift-profile

        # Set the TEST_DATABASE in your CI
        dbname: {% raw %}"{{ env_var('DBT_DATABASE') }}"{% endraw %}
        schema: {{ cookiecutter.target_schema }}

        # Set variable DBT_USER in your CI
        user: {% raw %}"{{ env_var('DBT_USER') }}"{% endraw %}

        # Set variable DBT_PASSWORD in your CI
        password: {% raw %}"{{ env_var('DBT_PASSWORD') }}"{% endraw %}

        # Set variable DBT_REDSHIFT_ACCOUNT in your CI
        host: {% raw %}"{{ env_var('DBT_HOST') }}"{% endraw %}

        port: 5439
        keepalives_idle: 10 # default 0, indicating the system default
        # search_path: public # optional, not recommended
        # sslmode: [optional, set the sslmode used to connect to the database (in case this parameter is set, will look for ca in ~/.postgresql/root.crt)]
        {%- endif %}

